name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Run lint checks
        run: ./gradlew lintDebug --stacktrace

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v5
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 7

      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html
          retention-days: 7

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: test-reports
          path: app/build/reports/tests/testDebugUnitTest/
          retention-days: 7
